# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Skip CI')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get Path
        id: getPath
        run: |      
          files=$(git diff-tree --no-commit-id --name-only -r -m ${{ github.sha }} | grep metadata/ | xargs)
          for a in $files
            do
                if [[ $a == *"metadata"* ]]; then
                    pathvar=${a%/*}
                    echo "::set-output name=path::$pathvar"
                    break
                fi

            done
          
      - name: Bump Version
        if: github.ref == 'refs/heads/main'
        run: chmod +x ./scripts/version.sh && ./scripts/version.sh ${{ steps.getPath.outputs.path }}
          
      - name: Generate Artifact.json file
        run: chmod +x ./scripts/commit.sh && ./scripts/commit.sh ${{ steps.getPath.outputs.path }}